# Generated by Django 3.0.5 on 2020-05-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200506_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/Users/SamuelHohenshell/Desktop/rp_portfolio/projects/static/images/'),
        ),
    ]
