# Generated by Django 3.0.5 on 2020-05-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200506_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
